# Generated by Django 2.0.2 on 2020-06-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='summary',
        ),
        migrations.AddField(
            model_name='project',
            name='body',
            field=models.TextField(default='details'),
        ),
        migrations.AddField(
            model_name='project',
            name='title',
            field=models.CharField(default='project title', max_length=200),
        ),
    ]
