# Generated by Django 2.0.2 on 2020-06-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200604_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='body',
        ),
    ]
