# Generated by Django 2.0.2 on 2020-06-06 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='body',
        ),
    ]
